# Your Solution
version: '3'
services:

  book_catalog:
    image: book_catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - DATABASE_URL=postgresql://rongdu72_user:vCLguyRHodTIm0Tt4WiFKsun3ztsdFin@dpg-crlvhmjv2p9s73e5iil0-a.oregon-postgres.render.com/rongdu72
    restart: "no"

  inventory_management:
    image: inventory_management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
     - "4002:80"
    environment:
      - PORT=80
      - DATABASE_URL=postgresql://rongdu72_user:vCLguyRHodTIm0Tt4WiFKsun3ztsdFin@dpg-crlvhmjv2p9s73e5iil0-a.oregon-postgres.render.com/rongdu72
    restart: "no"