# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: rongdu88.azurecr.io/book_catalog:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "postgresql://rongdu72_user:vCLguyRHodTIm0Tt4WiFKsun3ztsdFin@dpg-crlvhmjv2p9s73e5iil0-a.oregon-postgres.render.com/rongdu72"

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: rongdu88.azurecr.io/inventory_management:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "postgresql://rongdu72_user:vCLguyRHodTIm0Tt4WiFKsun3ztsdFin@dpg-crlvhmjv2p9s73e5iil0-a.oregon-postgres.render.com/rongdu72"

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

 